markdown: rdiscount
pygments: true
permalink: /:year/:month/:day/:title.html
name: "Zhenlong"
markdown: kramdown

author: "Zhenlong"
atom-baseurl: "http://zhenlonghe.github.io/"
disqus: "zhenlonghe"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  # - title: Tags
  #   class: fa fa-tags
  #   href: /tags.html
  - title: RSS
    class: fa fa-rss
    href: /atom.xml
  - title: Theme
    class: fa-regular theme-icon fa-moon
    href: javascript:toggleTheme();
  - title: About
    class: fa fa-user
    href: /about.html
  # - title: Gallery
  #   class: fa fa-film
  #   href: https://www.flickr.com/photos/127518998@N02/
  # - title: Blogroll
  #   class: fa fa-link
  #   href: /links.html